---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: ns-redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 26379
  selector:
    app: redis
