apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx
  type: LoadBalancer
#  type: NodePort