apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-web
  namespace: default
spec:
  rules:
    - host: my-web.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-web
                port:
                  number: 80
